name: Simple Usage

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: pwd
      - run: ls -a
      - uses: docker://pandoc/core:2.9
        with:
          # args: "--help" # gets appended to pandoc command
          args: Linux0.org -f org -t html -s -o Linux0.html